# Generated by Django 4.2 on 2024-07-25 07:04

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import polls.models.poll
import polls.models.user_history


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(validators=[polls.models.poll.validate_expiry_date]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'REGULAR'), (2, 'ADMIN')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='userpollhistory',
            name='voting_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[polls.models.user_history.validate_not_future_date]),
        ),
    ]
