# Generated by Django 4.2 on 2024-07-25 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polls.models.poll


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_category_name_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL, validators=[polls.models.poll.validate_admin_user]),
        ),
    ]
