# Generated by Django 4.2 on 2024-08-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='userpollhistory',
            options={'verbose_name_plural': 'User Poll History'},
        ),
        migrations.AlterModelOptions(
            name='usertaghistory',
            options={'verbose_name_plural': 'User Tag History'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll'),
        ),
    ]
