# Generated by Django 4.2 on 2024-08-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_choice_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='vote_count',
        ),
    ]
