# Generated by Django 4.2 on 2024-09-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('poll', 'choice_text')},
        ),
    ]
